### ISSUE TITLE
about thumb bug

### ISSUE THREAD

**Issue by arturparkhisenko** [gregmolnar/yii-attachment-behavior#10]
When i upload JPG file, its creates 2 files (original+thumb).
When later i upload PNG file, its creates same 2 files, and old JPG original - deleted and created new original PNG, in case of thumb, there is a bug: thumb file with JPG dont deleted, and created new PNG.
in the end i have 3 files, 1.png, 1-thumb.png, and dont deleted 1-thumb.jpg.

**Comment by gregmolnar** [comment]
I have a guess what's causing this but since I am not using this extension anymore nor PHP it will take some time to fix this as it has a low priority for me. A PR from anyone is welcomed.

**Comment by craigpotter** [comment]
Will write a pull request for this now and upload later

**Comment by 917K** [comment]
I have my solution for this problem. In AttachmentBehavior.php in method afterSave after this row:

``` php
if(file_exists($this->Owner->{$this->attribute}))unlink($this->Owner->{$this->attribute});
```

I've just put some piece of my code:

``` php
               $pathInfo = pathinfo($this->Owner->{$this->attribute});
                $ext = $pathInfo['extension'];
                $filename = $pathInfo['filename'];
                $dirname = $pathInfo['dirname'];
                $thumbFile = $dirname.'/'.$filename.'-thumb.'.$ext;
                if(file_exists($thumbFile))unlink($thumbFile);
```

Doesn't look gracefully, but it work. If someone has more elegant solution, please make a PR or just show it here
