### ISSUE TITLE
Form Save Error

### ISSUE THREAD

**Issue by skworden** [gregmolnar/yii-attachment-behavior#5]
I get this every time I save when using a form and the 'filename' field isn't on the from or the 'filename' field is a hiddenfield. 

Asset is my model

PHP notice

Undefined index: Asset 

C:\xampp\htdocs\assistsme1\protected\extensions\AttachmentBehavior\AttachmentBehavior.php(247)

235         if($name != $this->attribute)
236             parent::onUnsafeAttribute($name, $value);
237     }
238 }
239 
240 class AttachmentUploadedFile
241 {
242     public $name, $_error ;
243  
244     public static function getInstance($model, $attribute){
245         $c =  new AttachmentUploadedFile;
246         $c->modelName = get_class($model);
247         $c->name = $_FILES[$c->modelName]['name'][$attribute];
248         $c->file_name = $_FILES[$c->modelName]['tmp_name'][$attribute];
249         if(!file_exists($c->file_name))return null;
250         return $c;
251     }
252  
253     public function saveAs($file){
254         if($this->_error==UPLOAD_ERR_OK){
255             if(is_uploaded_file($this->file_name)){
256                 return move_uploaded_file($this->file_name, $file);
257             }else{
258                 return rename($this->file_name, $file);  
259             }            

Stack Trace
#0

–
 C:\xampp\htdocs\assistsme1\protected\extensions\AttachmentBehavior\AttachmentBehavior.php(143): AttachmentUploadedFile::getInstance(Asset, "filename")

138     }
139  
140  
141     public function afterSave($event)
142     {
143         $file = AttachmentUploadedFile::getInstance($this->Owner,$this->attribute);
144         if(!is_null($file)){
145             if(!$this->Owner->isNewRecord){
146                 //delete previous attachment
147                 if(file_exists($this->Owner->{$this->attribute}))unlink($this->Owner->{$this->attribute});
148             }else{
#1

+
 C:\xampp\htdocs\framework\base\CComponent.php(558): AttachmentBehavior->afterSave(CEvent)
#2

+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(838): CComponent->raiseEvent("onAfterSave", CEvent)
#3

+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(918): CActiveRecord->onAfterSave(CEvent)
#4

+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1072): CActiveRecord->afterSave()
#5

+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(795): CActiveRecord->update(null)
#6

–
 C:\xampp\htdocs\assistsme1\protected\modules\asset\controllers\AssetController.php(177): CActiveRecord->save()

172 
173         if(isset($_POST['Asset']))
174         {
175             $model->checked_out_status = '1';
176             $model->filename= '';
177             if($model->save())
178                 $this->redirect(array('view','id'=>$model->id));
179         }
180         else {
181                   // set defaults
182                   $model->checked_out_status = '1';

**Comment by gregmolnar** [comment]
I'll fix this. Thanks

**Comment by gregmolnar** [comment]
I fixed this on master. Please test it and let me know if you still have issues.
Thanks

**Comment by skworden** [comment]
Undefined variable: c

C:\xampp\htdocs\assistsme1\protected\extensions\AttachmentBehavior\AttachmentBehavior.php(245)

233     {
234         var_dump(true);exit;
235         if($name != $this->attribute)
236             parent::onUnsafeAttribute($name, $value);
237     }
238 }
239 
240 class AttachmentUploadedFile
241 {
242     public $name, $_error ;
243  
244     public static function getInstance($model, $attribute){
245         if(empty($_FILES[$c->modelName]['name'][$attribute]))return null;
246         $c =  new AttachmentUploadedFile;
247         $c->modelName = get_class($model);
248         $c->name = $_FILES[$c->modelName]['name'][$attribute];
249         $c->file_name = $_FILES[$c->modelName]['tmp_name'][$attribute];
250         if(!file_exists($c->file_name))return null;
251         return $c;
252     }
253  
254     public function saveAs($file){
255         if($this->_error==UPLOAD_ERR_OK){
256             if(is_uploaded_file($this->file_name)){
257                 return move_uploaded_file($this->file_name, $file);

Stack Trace
#0  
–
 C:\xampp\htdocs\assistsme1\protected\extensions\AttachmentBehavior\AttachmentBehavior.php(143): AttachmentUploadedFile::getInstance(Asset, "filename")

138     }
139  
140  
141     public function afterSave($event)
142     {
143         $file = AttachmentUploadedFile::getInstance($this->Owner,$this->attribute);
144         if(!is_null($file)){
145             if(!$this->Owner->isNewRecord){
146                 //delete previous attachment
147                 if(file_exists($this->Owner->{$this->attribute}))unlink($this->Owner->{$this->attribute});
148             }else{

#1  
+
 C:\xampp\htdocs\framework\base\CComponent.php(558): AttachmentBehavior->afterSave(CEvent)
#2  
+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(838): CComponent->raiseEvent("onAfterSave", CEvent)
#3  
+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(918): CActiveRecord->onAfterSave(CEvent)
#4  
+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1072): CActiveRecord->afterSave()
#5  
+
 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(795): CActiveRecord->update(null)
#6  
–
 C:\xampp\htdocs\assistsme1\protected\modules\asset\controllers\AssetController.php(172): CActiveRecord->save()

**Comment by skworden** [comment]
it lets you access the form now however, it now throws the undefined index c

**Comment by skworden** [comment]
also, is there a way to keep the background transparent on png on upload or at least change it to white? It fills it black currently.  Thank you!

**Comment by gregmolnar** [comment]
the undefined index is fixed now but please test it.
Regards the PNG I will make some tests and check what's wrong.
