### ISSUE TITLE
Image cases

### ISSUE THREAD

**Issue by skworden** [gregmolnar/yii-attachment-behavior#7]
I was uploading images from my iphone and it makes the ext. JPG and not jpg so it throws an error.

I added the capital version for all of them ie.
case "JPG";
                $original = imagecreatefromjpeg($this->image);
                $output_function = 'imagejpeg';
            break;

**Comment by craigpotter** [comment]
See my pull request. Better solution than adding upper and lower case switch cases

**Comment by gregmolnar** [comment]
@craigpotter thanks
